name: Build Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build_feature:
    name: Build Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            name: linux
            testExe: build/sst-basic-blocks-test
            cmakeArgs:

          - os: macos-latest
            name: mac-x86
            testExe: build/sst-basic-blocks-test
            cmakeArgs: -DCMAKE_OSX_ARCHITECTURES=x86_64


          - os: macos-latest
            name: mac-arm
            testExe: echo "unrunnable"
            cmakeArgs: -DCMAKE_OSX_ARCHITECTURES=arm64

          - os: macos-latest
            name: mac-arm-nonative
            testExe: echo "unrunnable"
            cmakeArgs: -DCMAKE_OSX_ARCHITECTURES=x86_64 -D

          - os: windows-latest
            name: win
            testExe: build/Release/sst-basic-blocks-test.exe

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Smoke test
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release ${{ matrix.cmakeArgs }} -DSST_BASIC_BLOCKS_BUILD_TESTS=TRUE 
          cmake --build ./build --config Release

      - name: Run Smoke Test
        run: |
          ls ${{ matrix.testExe }}
          ${{ matrix.testExe }}
